name: example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  my_flutter_plugin:
    git:
      url: https://gitee.com/luoyi666/my_flutter_plugin.git
  extended_image: ^8.2.0
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  super_sliver_list: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

dependency_overrides:
  my_flutter:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/iconfont.ttf

