name: material_app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  my_flutter:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
  my_flutter_plugin:
    git:
      url: https://gitee.com/luoyi666/my_flutter_plugin.git
  extended_image: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/iconfont.ttf

