include: package:flutter_lints/flutter.yaml

# 自定义语法校验规则
linter:
  rules:
    # 关闭forEach的校验。很多情况下，dart推荐你使用for循环遍历数组而不是forEach，但dart并没有说明有什么性能问题、或其他缺陷
    avoid_function_literals_in_foreach_calls: false
    # 关闭以下划线分割变量名的校验，即：xxx_xxx
    non_constant_identifier_names: false
    # 关闭局部变量前导下划线的校验，即：_xxx
    no_leading_underscores_for_local_identifiers: false
