name: my_flutter
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flustars: ^2.0.1
  fluttertoast: ^8.2.2
  get: ^4.6.6
  go_router: ^12.1.1
  logger: ^2.0.2+1
  multi_split_view: ^2.4.0
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  path: ^1.8.3
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
