name: my_flutter
description: "A new Flutter project."
version: 0.0.4
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.3
  get: ^5.0.0-release-candidate-5
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  collection: ^1.18.0
  modal_bottom_sheet: ^3.0.0-pre
  extended_tabs: ^4.1.0
  flutter_spinkit: ^5.2.0
  flutter_platform_widgets: ^6.0.2
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.0

  highlight_text: ^1.7.0
  faker: ^2.1.0
  shimmer: ^3.0.0
  open_file_plus: ^3.4.1
  flustars: ^2.0.1
  fluttertoast: ^8.2.4
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  path: ^1.8.3
  html: ^0.15.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
