name: my_flutter
description: "A new Flutter project."
version: 1.1.4
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^5.0.0-release-candidate-5
  dio: ^5.4.0
  collection: ^1.18.0
  flustars: ^2.0.1
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1
  path: ^1.8.3
  html: ^0.15.4
  hive_flutter: ^2.0.0-dev
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

dependency_overrides:
  hive: ^3.0.0-dev

flutter:
  uses-material-design: true
