name: my_flutter
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
      path: package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
