name: my_flutter
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flustars: ^2.0.1
  fluttertoast: ^8.2.2
  get: ^4.6.6
  go_router: ^12.1.1
  logger: ^2.0.2+1
  multi_split_view: ^2.4.0
  uuid: ^3.0.7
  path: ^1.8.3
  html: ^0.15.4
  permission_handler: ^11.1.0
  vibration: ^1.8.3
  extended_tabs: ^4.1.0
  modal_bottom_sheet: ^3.0.0-pre
  azlistview: ^2.0.0
  lpinyin: ^2.0.3
  scrollable_positioned_list: ^0.2.3
  highlight_text: ^1.7.0
  flutter_animate: ^4.3.0
  collection: ^1.18.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  get_storage: ^2.1.1
  flutter_phoenix: ^1.1.1
  webview_flutter: ^4.4.2
  status_bar_control: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
