name: my_flutter
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  my_flutter_common:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
      path: my_flutter_common
  my_flutter_page:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
      path: my_flutter_page
  my_flutter_plugin:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
      path: my_flutter_plugin
  my_flutter_util:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
      path: my_flutter_util
  my_flutter_widget:
    git:
      url: https://gitee.com/luoyi666/my_flutter.git
      path: my_flutter_widget

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
