name: my_flutter
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  my_flutter_common:
    path: ./my_flutter_common
  my_flutter_page:
    path: ./my_flutter_page
  my_flutter_plugin:
    path: ./my_flutter_plugin
  my_flutter_util:
    path: ./my_flutter_util
  my_flutter_widget:
    path: ./my_flutter_widget
  multi_split_view: ^2.4.0
  status_bar_control: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
