name: my_flutter_widget
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  my_flutter_common:
    path: ../my_flutter_common
  my_flutter_util:
    path: ../my_flutter_util
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  modal_bottom_sheet: ^3.0.0-pre
  extended_tabs: ^4.1.0
  scrollable_positioned_list: ^0.2.3
  azlistview: ^2.0.0
  lpinyin: ^2.0.3
  highlight_text: ^1.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

