name: my_flutter_plugin
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^5.0.0-release-candidate-5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
