name: package
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^5.0.0-release-candidate-5
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  collection: ^1.18.0
  modal_bottom_sheet: ^3.0.0-pre
  extended_tabs: ^4.1.0
  flutter_animate: ^4.3.0
  flutter_spinkit: ^5.2.0
  flutter_platform_widgets: ^6.0.2
  cached_network_image: ^3.3.0
  scrollable_positioned_list: ^0.2.3
  azlistview: ^2.0.0
  lpinyin: ^2.0.3
  highlight_text: ^1.7.0
  faker: ^2.1.0
  shimmer: ^3.0.0
  go_router: ^12.1.3
  event_bus: ^2.0.0
  flustars: ^2.0.1
  fluttertoast: ^8.2.4
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  uuid: ^3.0.7
  path: ^1.8.3
  html: ^0.15.4
  vibration: ^1.8.4
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  multi_split_view: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

