name: my_flutter_util
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  event_bus: ^2.0.0
  flustars: ^2.0.1
  fluttertoast: ^8.2.4
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  uuid: ^3.0.7
  path: ^1.8.3
  html: ^0.15.4
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
