name: build web page

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          architecture: x64
      - run: sh ./script/example.sh
      - name: Deploy Web
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: flutter_web_pages
          folder: build/web
          clean: true
